### ISSUE TITLE
位置问题

### ISSUE THREAD

**Issue by Grandpa-proud-cannot-beat-me** [JokingAboutLife/navicat-premium-linux-reset#2]
这个脚本放在哪里执行都可以吗

**Comment by oomeow** [comment]
> 这个脚本放在哪里执行都可以吗

需要管理员权限的目录下是不能执行脚本的，建议放在普通用户目录下。

该脚本运行所产生的日志和相关重置信息的json文件都在该脚本所在的目录中产生，所以只要满足上面条件，该脚本放在哪里都行
